apiVersion: apps/v1
kind: Deployment
metadata:
  name: Jenkinsjava
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: rohansharma91/jenkinsjavatest:replace
        ports:
        - containerPort: 80

